apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: results-app
  name: results-app
spec:
  ports:
  - name: "7070"
    port: 7070
    targetPort: 80
  selector:
    io.kompose.service: results-app
status:
  loadBalancer: {}
