---

apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: HRK
    type: database
spec:
  containers:
    - name: postgres-container
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: 123456_U
        - name: POSTGRES_USER
          value: HRK
        - name: POSTGRES_DB
          value: mydb
