---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    type: proxy
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
        - key: slave1
          operator: Equal
          value: taint1
          effect: NoSchedule
...
