---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    type: appserver
    author: Hrithik
spec:
  replicas: 2
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: tomcat-containers
          image: tomee
      tolerations:
        - key: slave2
          operator: Equal
          value: taint2
          effect: NoSchedule
